Apply bin optimizations to msgpack_unpacker
AdRoll/msgpack-erlang pull request #1
Opened 2022-08-10 15:12 UTC by tak30

Before the change:
```
Erlang/OTP 24 [erts-12.3.2.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

Eshell V12.3.2.2  (abort with ^G)
1> msgpack_bench:bench().
Done 1000 iterations, took 66 ms
2> msgpack_bench:bench(100000).
Done 100000 iterations, took 15669 ms
3> msgpack_bench:bench(10000000).
Done 10000000 iterations, took 865086 ms
```

After the change:
```
 Erlang/OTP 24 [erts-12.3.2.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

Eshell V12.3.2.2  (abort with ^G)
1> msgpack_bench:bench().
Done 1000 iterations, took 53 ms
2> msgpack_bench:bench(100000).
Done 100000 iterations, took 13041 ms
3> msgpack_bench:bench(10000000).
Done 10000000 iterations, took 747537 ms
4>

```

Benchmark code:

```erl
-module(msgpack_bench).

-export([bench/0, bench/1]).

bench() ->
    bench(1000).

bench(Iterations) ->
    {ok, TestData} = file:read_file("/tmp/pokedex.json"),
    TestDataDecoded = jiffy:decode(TestData),
    TestDataPacked = msgpack:pack(TestDataDecoded),
    {Time, _} = timer:tc(fun() -> [ begin
        msgpack:unpack(TestDataPacked),
        ok
    end || _ <- lists:seq(0, Iterations)]
    end),

    io:format("Done ~p iterations, took ~p ms", [Iterations, Time]).

```

Json used for the benchmark: https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json

2022-08-10 16:04 UTC, juanbono approved these changes

2022-08-10 16:13 UTC, raz-adroll approved these changes

2022-08-10 16:14 UTC, raz-adroll commented
Shared by @tak30 on how these optimizations work:
https://www.erlang.org/doc/efficiency_guide/binaryhandling.html
https://rhye.org/post/erlang-binary-matching-performance/

2022-08-11 07:31 UTC, elbrujohalcon approved these changes

2022-08-11 07:32 UTC, elbrujohalcon requested changes
Can you put comments on those binary matches (at least in some of them) so future me doesn't say _"hey… we can simplify this by removing the `/binary` pieces since it's the same anyway"_? 🙏🏻

2022-08-11 07:46 UTC, pablocostass approved these changes

2022-08-11 08:56 UTC, tak30 commented
> Can you put comments on those binary matches (at least in some of them) so future me doesn't say _"hey… we can simplify this by removing the `/binary` pieces since it's the same anyway"_? 🙏🏻

Done!

2022-08-11 08:59 UTC, elbrujohalcon approved these changes

2022-08-11 09:06 UTC, merged